### ISSUE TITLE
Feature Request - Auto Tagging

### ISSUE THREAD

**Issue by justinokay** [kurt-culley/ScrapeTrainV2#1]
Hello Kurt,

Not sure if this the best place to request features. I donated few months back. Really enjoy your application. How hard would it be to tag the mp3 files with track number, title, album, artist etc?

**Comment by kurt-culley** [comment]
Hi again, I have just pushed a new version with ID3 tagging. Let me know if you are happy with the way album artwork is handled as I was not sure if I should use the artist's profile image or the image usually presented in the playlist. For now I have gone with the latter, though it will still default to the artist's profile image if the playlist image is not present. I was also unsure if you wanted to manually set the album name, currently set to 'Traktrain', or rather extract the album name from the first downloaded track (if present) and then set the rest to be the same. Please note I have also changed over to using Bundler to handle dependencies.
