### ISSUE TITLE
no longer works as of 9/1/2020

### ISSUE THREAD

**Issue by suzu333** [kurt-culley/ScrapeTrainV2#7]
title implies all.
whenever you try and download tracks it creates the directory, but no longer detects any beats on an artists page. 

[INFO] Artist: 'x'
[INFO] Track count: 0
[INFO] Building track hash array, please wait.
[INFO] Creating directory 'x' if it does not already exist.

checked on several different accounts with beats on them and can confirm not working.

**Comment by bad-dub** [comment]
having the same issue seems to be due to a website update

**Comment by kurt-culley** [comment]
Please see - https://github.com/kurt-culley/ScrapeTrainV2/issues/8#issuecomment-703150812
Will be closing this issue as it's a dupe, but I'll keep issue #8 open for now if you have any more questions 🙂
